In [ ]:
import numpy as np

In [ ]:
#checking the numpy version
import numpy
print(numpy.__version__)

1.21.6


In [ ]:
#creating an array in numpy
import numpy as np
arr=print(np.array([1,2,3,4]))



[1 2 3 4]


**QUESTION:-WAP IN PYTHON TO SHOW THE TYPECASTING IN ARRAY**

In [ ]:
#typecasting the data type of array
import numpy as np
b=print(np.array([1,2,3,4],dtype='f'))


[1. 2. 3. 4.]


**QUESTION:-WAP IN PYTHON TO CREATE AN 2D ARRAY**

In [ ]:
#creating the 2d array
import numpy as np
a=[[1,2,3,4,5,6],[7,8,9,10,11,12]]
b=print(np.array(a))



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


**QUESTION:-WAP IN PYTHON TO CREATE AN EMPTY ARRAY(FULL OF GARBAGE VALUE)**

In [ ]:
#creating an empty array 
import numpy as np
arr=np.empty([3,4])
arr



array([[4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.0e-323],
       [4.4e-323, 4.9e-323, 5.4e-323, 5.9e-323]])

In [ ]:
#creating an full array
import numpy as np
a=print(np.full([3,3],1))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


**QUESTION:-WAP IN PYTHON TO CREATE A ARRAY FULL OF ZEROS**

In [ ]:
#creating an array full of zeros
import numpy as np
a=print(np.zeros([2,2]))

[[0. 0.]
 [0. 0.]]


**QUESTION:-WAP IN PYTHON TO CREATE AN ARRAY FULL OF ONES**

In [ ]:
#creating an array full of ones
import numpy as np
a=print(np.ones([2,2]))

[[1. 1.]
 [1. 1.]]


**QUESTION:- WAP IN OYTHON TO CREATE A 3D ARRAY**

In [ ]:
#creating an 3-d array
import numpy as np
a1=np.array([1,2,3,4],ndmin=3)
a1

array([[[1, 2, 3, 4]]])

**QUESTION:-WAP IN PYTHON TO FIND THE MAX VALUE AND MIN VALUE OF NUMPY ARRAY**

In [ ]:
#finding the max and min value of numpy array
import numpy as np
a=np.array([1,2,3,4,5])
m=a.max()
mi=a.min()
print("the max value and min value of this array is ",m,mi)

the max value and min value of this array is  5 1


***QUESTION:- Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.***

In [ ]:
#finding the difference of max value and min value of array along second axis
import numpy as np
a=np.array(([1,2,3,4,5],[6,7,8,9,10]))
print(a)
m=np.amax(a,1)
mi=np.amin(a,1)
difference=m-mi
print("the difference between the max value and min value of the array along the second axis is ",difference)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
the difference between the max value and min value of the array along the second axis is  [4 4]


**QUESTION:-WAP IN PYTHON TO FIND THE MAXIMUM AND MINIMUM VALUE OF AN FLATTENED ARRAY**

In [ ]:
#finding the max value and min value of flattened array
import numpy as np
q=np.array(([1,2,3,4,5],[6,7,8,9,10]))
print(q)
f=np.ndarray.flatten(q)
print("the flattened array is ",f)
ma=f.max()
mi=f.min()
print("the max and min value of flattened array is ",ma,mi)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
the flattened array is  [ 1  2  3  4  5  6  7  8  9 10]
the max and min value of flattened array is  10 1


***QUESTION:-WAP IN PYTHON TO COUNT THE OCCURENCE OF 'P' IN GIVEN ARRAY ***

In [ ]:
#finding the frequency of 'p' in given array
import numpy as np
c=[]
a=np.array(['p','q','r','t','p','y','p'])
for i in a:
  if i =='p':
    c.append(i)
frequency=len(c)
print("the number of occurences of 'p' in the given array is ",frequency)

the number of occurences of 'p' in the given array is  3


**QUESTION:-WAP IN PYTHON TO REPLACE 'PHP' WITH 'PYTHON' IN THE GIVEN ARRAY**

In [ ]:
#replacing 'python' with 'php'
import numpy as np
a=np.array(['html','java','python','harry'])
print(a)
a[2]='php'
print("the updated array is",a)

['html' 'java' 'python' 'harry']
the updated array is ['html' 'java' 'php' 'harry']


**QUESTION:-WAP IN PYTHON TO COUNT THE OCCURENCE OF EACH VALUE IN GIVEN ARRAY**

In [ ]:
#counting the frequency of each element in given array
import numpy as np
a=np.array([1,2,3,4,2,1])
arr_bins = np.bincount(a)
print(arr_bins)
len(arr_bins)

[0 2 2 1 1]


5

**QUESTION:-WAP IN PYTHON TO COUNT HE NUMBER OF ELEMENTS IN ARRAY**

In [ ]:
#counting the number of elements of array(non zero elements)
import numpy as np
a=np.array([1,2,3,4,5,6])
np.count_nonzero(a)

6

**QUESTION:-WAP IN PYTHON TO DO SORTING OON FLATTENED ARRAY**

In [ ]:
#sorting of flattened array 
import numpy as np
a=np.array(([98,55,52,4,48],[88,2,47,120,989]))
f=np.ndarray.flatten(a)
np.sort(f)

array([  2,   4,  47,  48,  52,  55,  88,  98, 120, 989])